name: examples

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.rst'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "arduino-blink"
          - "arduino-external-libs"
          - "arduino-internal-libs"
          - "arduino-mbed-doom"
          - "arduino-mbed-rpc"
          - "arduino-mxchip-azureiot"
          - "arduino-mxchip-filesystem"
          - "arduino-mxchip-sensors"
          - "arduino-mxchip-wifiscan"
          - "cmsis-blink"
          - "libopencm3-1bitsy"
          - "libopencm3-blink"
          - "libopencm3-usb-cdcacm"
          - "mbed-rtos-blink-baremetal"
          - "mbed-rtos-custom-target"
          - "mbed-rtos-ethernet-tls"
          - "mbed-rtos-events"
          - "mbed-rtos-filesystem"
          - "mbed-rtos-mesh-minimal"
          - "mbed-rtos-serial"
          - "mbed-rtos-sockets"
          - "mbed-rtos-usb-keyboard"
          - "spl-blink"
          - "stm32cube-hal-blink"
          - "stm32cube-hal-eeprom-emulation"
          - "stm32cube-hal-extmem-boot"
          - "stm32cube-hal-iap"
          - "stm32cube-hal-lcd"
          - "stm32cube-hal-usb-device-dfu"
          - "stm32cube-hal-wifi-client"
          - "stm32cube-ll-blink"
          - "zephyr-blink"
          - "zephyr-cpp-synchronization"
          - "zephyr-drivers-can"
          - "zephyr-net-https-client"
          - "zephyr-subsys-usb-hid-mouse"
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          submodules: "recursive"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'
            architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install -U https://github.com/os-q/pio/archive/develop.zip
          pio pkg install --global --platform symlink://.

      - name: Build examples
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}
